# Prettier friendly markdownlint config (all formatting rules disabled)
extends: markdownlint/style/prettier
first-line-heading:
  severity: warning
fenced-code-language: false
no-emphasis-as-heading: false
no-inline-html: false
no-duplicate-heading: false
heading-start-left: false
